marketplace_app/info/urls.py
"""marketplace_app.info URL Configuration
"""
from django.urls import path
from .views import AboutView

app_name = "info"

urlpatterns = [
    path("about/", AboutView.as_view(), name="about"),
]

marketplace_app/marketplace_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("", include("user.urls", namespace="user")),
    path("", include("shop.urls", namespace="shop")),
    path("", include("order.urls", namespace="order")),
    path("", include("discount.urls", namespace="discount")),
    path("", include("info.urls", namespace="info")),
    path("", include("django.contrib.auth.urls")),
]

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:

    urlpatterns = [
        # path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace_app/product/urls.py
"""marketplace_app.product URL Configuration
"""
from django.urls import path
from product.views import IndexView, ProductListView, ProductDetailView

app_name = "product"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("catalog/", ProductListView.as_view(), name="list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="detail"),
]

marketplace_app/shop/urls.py
from django.urls import path

from .views import ContactsView, ShopDetailView, ShopListView


app_name = "shop"

urlpatterns = [
    path("contacts/", ContactsView.as_view(), name="contacts_detail"),
    path("shops/", ShopListView.as_view(), name="list"),
    path("shops/<int:pk>/", ShopDetailView.as_view(), name="detail"),
]

marketplace_app/user/urls.py
"""marketplace_app.user URL Configuration
"""
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from user import views

app_name = "user"

urlpatterns = [
    path("user/<int:pk>/account/", views.UserAccount.as_view(), name="user_account"),
    path("user/<int:pk>/profile/", views.UserProfile.as_view(), name="user_profile"),
    path(
        "user/<int:pk>/orders/", views.HistoryOrders.as_view(), name="user_orders_list"
    ),
    path("user/<int:pk>/views/", views.HistoryViews.as_view(), name="user_views"),
    path(
        "compare/category/<int:pk>/",
        views.CompareProduct.as_view(),
        name="compare_list",
    ),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password_reset/",
        views.PasswordResetViewCustom.as_view(),
        name="password_reset",
    ),
]

marketplace_app/shop/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Shop(models.Model):
    """Класс описывающий модель магазина"""

    name = models.CharField(verbose_name=_("name"), max_length=150)

    description = models.TextField(verbose_name=_("description"), blank=True)

    image = models.ImageField(
        verbose_name=_("image"), null=True, upload_to="shop_images/"
    )

    address = models.CharField(verbose_name=_("address"), max_length=150, blank=True)

    phone = models.CharField(verbose_name=_("phone"), max_length=15, blank=True)

    mobile = models.CharField(verbose_name=_("mobile"), max_length=15, blank=True)

    email_general = models.EmailField(verbose_name=_("general email"), blank=True)

    email_editor = models.EmailField(verbose_name=_("editor email"), blank=True)

    shipping_policy = models.CharField(
        verbose_name=_("shipping and returns policy"), max_length=50, blank=True
    )

    refund_policy = models.CharField(
        verbose_name=_("refund policy"), max_length=50, blank=True
    )

    support_policy = models.CharField(
        verbose_name=_("support policy"), max_length=50, blank=True
    )

    quality_policy = models.CharField(
        verbose_name=_("quality policy"), max_length=50, blank=True
    )

    objects = models.Manager()

    class Meta:
        ordering = ("name",)
        verbose_name = _("shop")
        verbose_name_plural = _("shops")

    def __str__(self):
        return "{name}".format(name=self.name)

marketplace_app/shop/models/shop.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Shop(models.Model):
    """Модель магазина"""
    name = models.CharField(
        _("name"),
        max_length=150
    )
    description = models.TextField(
        _("description"),
        blank=True
    )
    image = models.ImageField(
        _("image"),
        null=True,
        upload_to='shop_images/'
    )
    address = models.CharField(
        _("address"),
        max_length=150,
        blank=True
    )
    phone = models.CharField(
        _("phone"),
        max_length=15,
        blank=True
    )
    mobile = models.CharField(
        _("mobile"),
        max_length=15,
        blank=True
    )
    email_general = models.EmailField(
        _("general email"),
        blank=True
    )
    email_editor = models.EmailField(
        _("editor email"),
        blank=True
    )
    shipping_policy = models.CharField(
        _("shipping and returns policy"),
        max_length=50,
        blank=True
    )
    refund_policy = models.CharField(
        _("refund policy"),
        max_length=50,
        blank=True
    )
    support_policy = models.CharField(
        _("support policy"),
        max_length=50,
        blank=True
    )
    quality_policy = models.CharField(
        _("quality policy"),
        max_length=50,
        blank=True
    )

    objects = models.Manager()

    class Meta:
        ordering = ('name',)
        verbose_name = _("shop")
        verbose_name_plural = _("shops")

    def __str__(self) -> str:
        return "{name}".format(
            name=self.name
        )

marketplace_app/shop/forms.py
from django.core import mail
from django import forms
from django.utils.translation import ugettext_lazy

from marketplace_app.settings import DEBUG
from info.models import Settings


class FeedBackForm(forms.Form):
    """Форма обратной связи на странице контактов"""

    name = forms.CharField(
        min_length=5,
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-input",
                "id": "name",
                "name": "name",
                "placeholder": ugettext_lazy("name"),
            }
        ),
    )

    email = forms.CharField(
        min_length=5,
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-input",
                "id": "mail",
                "name": "mail",
                "placeholder": ugettext_lazy("e-mail"),
            }
        ),
    )

    site = forms.CharField(
        min_length=5,
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-input",
                "id": "site",
                "name": "site",
                "placeholder": ugettext_lazy("website"),
            }
        ),
    )

    message = forms.CharField(
        min_length=5,
        max_length=500,
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-textarea",
                "id": "message",
                "name": "message",
                "placeholder": ugettext_lazy("message"),
            }
        ),
    )

    def send_email(self) -> None:
        """Метод отправки письма из формы обратной связи"""
        connection: "EmailBackend" = None
        if DEBUG:
            connection = mail.get_connection(
                backend="django.core.mail.backends.console.EmailBackend"
            )
        else:
            host: str = (
                Settings.objects.only("value").get(name="feedback_mailing_host").value
            )
            port: str = (
                Settings.objects.only("value").get(name="feedback_mailing_port").value
            )
            username: str = (
                Settings.objects.only("value").get(name="feedback_mailing_login").value
            )
            password: str = (
                Settings.objects.only("value")
                .get(name="feedback_mailing_password")
                .value
            )
            tls_str: str = (
                Settings.objects.only("value")
                .get(name="feedback_mailing_tls_usage")
                .value
            )
            tls: bool = True if tls_str.lower() == "y" else False
            ssl_str: str = (
                Settings.objects.only("value")
                .get(name="feedback_mailing_ssl_usage")
                .value
            )
            ssl: bool = True if ssl_str.lower() == "y" else False
            from django.core.mail.backends.smtp import EmailBackend

            connection = EmailBackend(
                host=host,
                port=port,
                username=username,
                password=password,
                use_tls=tls,
                use_ssl=ssl,
                timeout=10,
                fail_silently=False,
            )
        reciever: str = (
            Settings.objects.only("value").get(name="feedback_mailing_email").value
        )
        body: str = "{name}\n{site}\n{msg}".format(
            name=self.cleaned_data["name"],
            site=self.cleaned_data["site"],
            msg=self.cleaned_data["message"],
        )
        connection.open()
        mail.EmailMessage(
            subject="Feedback form message",
            from_email=self.cleaned_data["email"],
            to=[reciever],
            body=body,
            connection=connection,
        ).send(fail_silently=False)
        connection.close()

marketplace_app/shop/views.py
from typing import Any, Dict
from django.apps import apps
from django.urls import reverse
from django.views import generic

from product.models import Stock
from .models import Shop
from .forms import FeedBackForm


Product = apps.get_model(app_label="product", model_name="Product")


class ShopListView(generic.ListView):
    """Представление списка магазинов"""

    model = Shop
    queryset = Shop.objects.all()
    context_object_name = "shops"
    paginate_by = 24


class ShopDetailView(generic.DetailView):
    """Представление объекта магазина"""

    model = Shop
    queryset = Shop.objects.all()
    context_object_name = "shop"

    def get_context_data(self, **kwargs):
        kwargs.setdefault("view", self)
        kwargs.update({"shop": self.get_object()})
        kwargs.update({"products": Product.get_popular(shop=self.get_object())})
        kwargs.update(
            {"stocks": Stock.get_products_in_stock_by_shop(self.get_object())},
        )

        return kwargs


class ContactsDetailView(generic.DetailView):
    """Класс рендеринта страницы контактов по запросу методом GET"""

    template_name = "shop/contacts_detail.html"
    context_object_name = "shop"

    def get_object(self, queryset=None):
        """Метод получения объекта магазина для вывода контактов"""
        return Shop.objects.get(id=1)

    def get_context_data(self, **kwargs):
        """Метод формирования контекста страницы (дабавление формы)"""
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context["form"] = FeedBackForm()
        return context


class ContactsFormView(generic.detail.SingleObjectMixin, generic.FormView):
    """Класс рендеринга страницы контактов магазина по запросу методом POST"""

    template_name = "shop/contacts_detail.html"
    context_object_name = "shop"
    form_class = FeedBackForm

    def get_object(self, queryset=None):
        """Метод получения объекта магазина для вывода контактов"""
        return Shop.objects.get(id=1)

    def get_success_url(self) -> str:
        """Метод получения страницы редиректа при успешной обработке формы"""
        return reverse("shop:contacts_detail")

    def form_valid(self, form):
        """Метод обработки валидной формы"""
        form.send_email()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ContactsView(generic.View):
    """Общий класс для рендеринга страницы контактов с формой"""

    def get(self, request, *args, **kwargs):
        """Метод перенаправления на класс при запросе типа GET"""
        view: generic.View = ContactsDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Метод перенаправления на класс при запросе типа POST"""
        view: generic.View = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

marketplace_app/shop/templates/shop/shop_card.html
{% load static %}
{% load i18n %}

<a class="Card-picture" href="{% url 'shop:detail' pk=shop.pk %}">
  <img src="{{ shop.image.url }}" alt="{{ shop.name }}"/>
</a>
<div class="Card-content">
  <strong class="Card-title">
    <a href="{% url 'shop:detail' pk=shop.pk %}">{{ shop.name }}</a>
  </strong>
</div>

marketplace_app/shop/templates/shop/shop_detail.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load cache %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{{ shop.name }}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% translate "home" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <a href="{% url 'shop:list' %}">{% translate "shops" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{{ shop.name }}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section Section_column Section_columnLeft Section_columnWide">
    <div class="wrap">
      <div class="Section-column">
        {% cache 86400 shop_info %}
        {% if shop.shipping_policy %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_advantage">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/advantages/shipping.svg' %}" alt="shipping.svg"/>
                </div>
                <div class="media-content">
                  <strong class="media-title">{% translate "shipping & returns" %}</strong>
                  <p class="media-text">{{ shop.shipping_policy }}</p>
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.refund_policy %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_advantage">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/advantages/moneyBack.svg' %}" alt="moneyBack.svg"/>
                </div>
                <div class="media-content">
                  <strong class="media-title">{% translate "money back" %}</strong>
                  <p class="media-text">{{ shop.refund_policy }}</p>
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.support_policy %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_advantage">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/advantages/support.svg' %}" alt="support.svg"/>
                </div>
                <div class="media-content">
                  <strong class="media-title">{% translate "support policy" %}</strong>
                  <p class="media-text">{{ shop.support_policy }}</p>
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.quality_policy %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_advantage">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/advantages/quality.svg' %}" alt="quality.svg"/>
                </div>
                <div class="media-content">
                  <strong class="media-title">{% translate "quality guarantee" %}</strong>
                  <p class="media-text">{{ shop.quality_policy }}</p>
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.phone or shop.mobile %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/contacts/phone.svg' %}" alt="phone.svg"/>
                </div>
                <div class="media-content"> 
                  {% if shop.phone %}
                  {% translate "phone"|capfirst %}:&#32;<nobr>{{ shop.phone }}</nobr><br>
                  {% endif %}
                  {% if shop.mobile %}
                  {% translate "mobile"|capfirst %}:&#32;<nobr>{{ shop.mobile }}</nobr>
                  {% endif %}
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.address %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/contacts/address.svg' %}" alt="address.svg"/>
                </div>
                <div class="media-content">
                    {{ shop.address }}
                </div>
              </div>
            </div>
        {% endif %}
        {% if shop.email_general or shop.email_editor %}
            <div class="Section-columnSection Section-columnSection_mark">
              <div class="media media_middle">
                <div class="media-image">
                  <img src="{% static 'assets/img/icons/contacts/mail.svg' %}" alt="mail.svg"/>
                </div>
                <div class="media-content">
                  {% if shop.email_general %}
                  {% translate "general"|capfirst %}: {{ shop.email_general }}<br>
                  {% endif %}
                  {% if shop.email_editor %}
                  {% translate "editor"|capfirst %}: {{ shop.email_editor }}
                  {% endif %}
                </div>
              </div>
            </div>
        {% endif %}
        {% endcache %}
        <div class="Section-columnSection">
          <header class="Section-header">
            <strong class="Section-title">{% translate "follow us" %}</strong>
          </header>
          <div class="Section-columnContent">
            <div class="Footer-payments Footer-payments_column">
              <div>
                <img src="{% static 'assets/img/icons/socialContent/fb.png' %}" alt="fb.png"/>
              </div>
              <div>
                <img src="{% static 'assets/img/icons/socialContent/tw.png' %}" alt="tw.png"/>
              </div>
              <div>
                <img src="{% static 'assets/img/icons/socialContent/gg.png' %}" alt="gg.png"/>
              </div>
              <div>
                <img src="{% static 'assets/img/icons/socialContent/in.png' %}" alt="in.png"/>
              </div>
              <div>
                <img src="{% static 'assets/img/icons/socialContent/pt.png' %}" alt="pt.png"/>
              </div>
              <div>
                <img src="{% static 'assets/img/icons/socialContent/ml.png' %}" alt="ml.png"/>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="Section-content">
        <div class="row row_verticalCenter row_maxHalf">
          <div class="row-block">
            <div class="pict">
              <img src="{{ shop.image.url }}" alt="{{ shop.name }}"/>
            </div>
          </div>
          <div class="row-block">
            <h2>{{ shop.name }}</h2>
            <p>{{ shop.description }}</p>
{#            <ul>#}
{#              <li>Lorem ipsum dolor sit amet, consectetuer#}
{#              </li>#}
{#              <li>adipiscing elit doli. Aenean commodo ligula#}
{#              </li>#}
{#              <li>eget dolor. Aenean massa. Cumtipsu sociis#}
{#              </li>#}
{#              <li>natoque penatibus et magnis dis parturient#}
{#              </li>#}
{#              <li>montesti, nascetur ridiculus mus. Donec#}
{#              </li>#}
{#              <li>quam felis, ultricies nec, pellentesque eutu#}
{#              </li>#}
{#            </ul>#}
          </div>
        </div>
        <header class="Section-header">
          <h2 class="Section-title">{% translate "popular products"|capfirst %}</h2>
        </header>
        <div class="Cards">
          {% if products %}
            {% cache 3600 shop_popular_products %}
            {% for product in products %}
              {% url 'product:detail' product.id as product_url %}
                <div class="Card">
                  {% include "card.html" %}
                </div>
            {% endfor %}
            {% endcache %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

marketplace_app/shop/templates/shop/shop_list.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% translate "shops" %}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% translate "home" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{% translate "shops" %}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section Section_column Section_columnLeft Section_columnWide">
    <div class="wrap">
      <div class="Section-content Section-content--p0">
        <div class="Cards">
          {% if shops %}
            {% for shop in shops %}
                <div class="Card">
                  {% include "shop/shop_card.html" %}
                </div>
            {% endfor %}
          {% else %}
            <div class="row row--column row_verticalCenter row_maxHalf">
              <div class="row-block">
                <h2>{% translate "There is no shops yet" %}
                </h2>
                <p>{% translate "But soon there will be" %}
                </p>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="Pagination">
          <div class="Pagination-ins">
            {% if page_obj.has_previous %}
              <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.previous_page_number }}">
                <img src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="<<"/>
              </a>
              <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.previous_page_number }}">
                <span class="Pagination-text">{{ page_obj.previous_page_number }}</span>
              </a>
            {% endif %}
            <span class="Pagination-element Pagination-element_current">
              <span class="Pagination-text">{{ page_obj.number }}</span>
            </span>
            {% if page_obj.has_next %}
              <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.next_page_number }}">
                <span class="Pagination-text">{{ page_obj.next_page_number }}</span>
              </a>
              <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.next_page_number }}">
                <img src="{% static 'assets/img/icons/nextPagination.svg' %}" alt=">>"/>
              </a>
            {% endif %}
          </div>
        </div>
{#        <div class="row row--column row_verticalCenter row_maxHalf">#}
{#            {% if shops %}#}
{#                {% for shop in shops %}#}
{#                  <div class="row-block">#}
{#                    <div class="pict">#}
{#                      <img src="{{ shop.image.url }}" alt="{{ shop.name }}"/>#}
{#                    </div>#}
{#                  </div>#}
{#                  <div class="row-block">#}
{#                    <h2><a href="{% url 'shop:detail' pk=shop.pk %}">{{ shop.name }}</a>#}
{#                    </h2>#}
{#                    <p>{{ shop.description }}#}
{#                    </p>#}
{#                  </div>#}
{#                {% endfor %}#}
{#            {% else %}#}
{#              <div class="row-block">#}
{#                <h2>There is no shops yet#}
{#                </h2>#}
{#                <p>But soon there will be#}
{#                </p>#}
{#              </div>#}
{#            {% endif %}#}
{#        </div>#}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}