marketplace_app/info/urls.py
"""marketplace_app.info URL Configuration
"""
from django.urls import path
from .views import AboutView

app_name = "info"

urlpatterns = [
    path("about/", AboutView.as_view(), name="about"),
]

marketplace_app/marketplace_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("", include("user.urls", namespace="user")),
    path("", include("shop.urls", namespace="shop")),
    path("", include("order.urls", namespace="order")),
    path("", include("discount.urls", namespace="discount")),
    path("", include("info.urls", namespace="info")),
    path("", include("django.contrib.auth.urls")),
]

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:

    urlpatterns = [
        # path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace_app/order/urls.py
"""marketplace_app.order URL Configuration
"""
from django.urls import path

from order import views

app_name = "order"

order_forms = getattr(views.OrderView, "order_forms", list())

urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/<int:pk>", views.AddToCartView.as_view(), name="add-to-cart"),
    path(
        "cart/add/<int:pk>/<int:cnt>",
        views.AddToCartView.as_view(),
        name="add-to-cart-cnt",
    ),
    path(
        "cart/add/<int:pk>/shop/<int:shop_id>",
        views.AddToCartView.as_view(),
        name="add-to-cart-shop",
    ),
    path(
        "cart/remove/<int:pk>",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
    path("order/<int:pk>/", views.OrderDetail.as_view(), name="order-detail"),
    path(
        "order/",
        views.OrderView.as_view(order_forms),
        name="order",
    ),
    path("order/<int:pk>/payment/", views.PaymentView.as_view(), name="payment"),
]

marketplace_app/product/urls.py
"""marketplace_app.product URL Configuration
"""
from django.urls import path
from product.views import IndexView, ProductListView, ProductDetailView

app_name = "product"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("catalog/", ProductListView.as_view(), name="list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="detail"),
]

marketplace_app/shop/urls.py
from django.urls import path

from .views import ContactsView, ShopDetailView, ShopListView


app_name = "shop"

urlpatterns = [
    path("contacts/", ContactsView.as_view(), name="contacts_detail"),
    path("shops/", ShopListView.as_view(), name="list"),
    path("shops/<int:pk>/", ShopDetailView.as_view(), name="detail"),
]

marketplace_app/user/urls.py
"""marketplace_app.user URL Configuration
"""
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from user import views

app_name = "user"

urlpatterns = [
    path("user/<int:pk>/account/", views.UserAccount.as_view(), name="user_account"),
    path("user/<int:pk>/profile/", views.UserProfile.as_view(), name="user_profile"),
    path(
        "user/<int:pk>/orders/", views.HistoryOrders.as_view(), name="user_orders_list"
    ),
    path("user/<int:pk>/views/", views.HistoryViews.as_view(), name="user_views"),
    path(
        "compare/category/<int:pk>/",
        views.CompareProduct.as_view(),
        name="compare_list",
    ),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password_reset/",
        views.PasswordResetViewCustom.as_view(),
        name="password_reset",
    ),
]

marketplace_app/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

marketplace_app/templates/base.html
{% load static %}
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!--> 
<html lang="ru"> 
  <!--<![endif]-->
  {% block head %}
    Head
  {% endblock %}
  <body class="Site">

    {% block header %}
      Header
    {% endblock %}

    {% block middle %}
      Middle
    {% endblock %}

    {% block footer %}
      Footer
    {% endblock %}

    {% block scripts %}
      Scripts
    {% endblock %}
  </body>
</html>

marketplace_app/templates/card.html
{% load static %}
{% load i18n %}

{% url 'product:detail' product.id as product_url %}
{% with product.discount as discount %}
<a class="Card-picture" href="{{ product_url }}">
  {% if product.image %}
  <img src="{{ product.image.url }}" alt="{{ product.title }}"/>
  {% endif %}
</a>
<div class="Card-content">
  <strong class="Card-title">
    <a href="{{ product_url }}">{{ product.title }}</a>
  </strong>
  <div class="Card-description">
    <div class="Card-cost">
      {% if discount.type %}
        <span class="Card-priceOld">${{ discount.base }}</span>
      {% endif %}
      {% if discount.base %}
      <span class="Card-price">${{ discount.price }}</span>
      {% else %}
      <span class="Card-price">{% trans 'The product is over' %}</span>
      {% endif %}
    </div>
    <div class="Card-category">{{ product.category }}</div>
    <div class="Card-hover">
      <a id="add-to-view" class="Card-btn product" href="{% url 'user:user_views' product.id %}">
        <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>
      </a>
        {% if "shops" in request.path %}
          {% for stock in stocks %}
            {% if stock.product == product %}
              <a id="add-to-cart"  class="Card-btn product" href="{% url 'order:add-to-cart-shop' product.id stock.id %}">
                <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
              </a>
            {% endif %}
          {% endfor %}
        {% else %}
          <a id="add-to-cart"  class="Card-btn product" href="{% url 'order:add-to-cart' product.id %}">
            <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
          </a>
        {% endif %}
        <a id="add-to-compare" class="Card-btn product" href="{% url 'user:compare_list' product.id %}">
          <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
        </a>

    </div>
  </div>
</div>
{% if discount.type %}
{% if discount.type == "P" %}
    <div class="Card-sale">-{{ discount.value }}%</div>
{% elif discount.type == "S" %}
    <div class="Card-sale">-{{ discount.value }}$</div>
{% elif discount.type == "F"  %}
    <div class="Card-sale">FIX</div>
{% endif %}
{% endif %}
{% endwith %}

marketplace_app/templates/footer.html
{% load static %}
{% load i18n %}
<footer class="Footer">
      <div class="wrap">
        <div class="row Footer-main">
          <div class="row-block">
            <a class="logo Footer-logo" href="{% url 'product:home' %}">
              <img class="logo-image" src="{% static 'assets/img/logo_footer.png' %}" alt="logo_footer.png"/>
            </a>
            <p>{% translate "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincid  unt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad" %}
            </p>
            <ul class="menu menu_img menu_smallImg Footer-menuSoc">
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/fb.svg' %}" alt="fb.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/tw.svg' %}" alt="tw.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/in.svg' %}" alt="in.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/pt.svg' %}" alt="pt.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/mail.svg' %}" alt="mail.svg"/>
                </a>
              </li>
            </ul>
          </div>
          <div class="row-block">
            <strong class="Footer-title">{% translate "Useful Links" %}</strong>
            <ul class="menu menu_vt Footer-menu">
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "checkout"|capfirst %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "My Cart" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "delivery"|capfirst %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Order Info" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Terms" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Conditions" %}</a>
              </li>
            </ul>
          </div>
          <div class="row-block">
            <strong class="Footer-title">{% translate "My Account" %}</strong>
            <ul class="menu menu_vt Footer-menu">
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Accessories" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Bags" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Cameras" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Clothings" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Electronics" %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">{% translate "Fashion" %}</a>
              </li>
            </ul>
          </div>
          <div class="row-block">
            <strong class="Footer-title">Contacts
            </strong>
            <p>{% translate "phone"|capfirst %}: 8.800.200.600
              <br>{% translate "e-mail"|capfirst %}: Support@ninzio.com
              <br>{% translate "skype"|capfirst %}: techno
              <br>{% translate "address"|capfirst %}: {% translate "New York, north" %}
              <br>{% translate "Avenue 26/7" %}
              <br>0057
            </p>
          </div>
        </div>
      </div>
      <div class="Footer-copy">
        <div class="wrap">
          <div class="row row_space">
            <div class="row-block">© {% translate "Copyright" %}&#32;
              <a href="{% url 'product:home' %}">Megano Store.
              </a>&#32;{% translate "All rights reserved." %}
            </div>
            <div class="row-block">
              <span>{% translate "Accepted Payments" %}
              </span>
              <div class="Footer-payments">
                <div>
                  <img src="{% static 'assets/img/payments/visa.png' %}" alt="visa.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/mastercard.png' %}" alt="mastercard.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/paypal.png' %}" alt="paypal.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/american.png' %}" alt="american.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/electron.png' %}" alt="electron.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/maestro.png' %}" alt="maestro.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/delta.png' %}" alt="delta.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/e.png' %}" alt="e.png"/>
                </div>
                <div>
                  <img src="{% static 'assets/img/payments/dk.png' %}" alt="dk.png"/>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

marketplace_app/templates/head.html
{% load static %}
<head>
    <title>{{seo.meta_title}}
    </title>
    <meta name="description" content="{{seo.meta_description}}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/alertify.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default.min.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}">
    </script>
    <!--[if lt IE 9]>
<script src="{% static 'http://html5shiv.googlecode.com/svn/trunk/html5.js' %}"></script><![endif]-->
</head>

marketplace_app/templates/header.html
{% load i18n %}
{% load static %}
{% load cache %}
{% load category_list %}
{% load user_tags %}

{% get_categories as categories %}

<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content"></div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<div class="ControlPanel">
  <div class="wrap">
    <div class="row ControlPanel-row">
      <div class="row-block">
        <div class="row ControlPanel-rowSplit">
          <div class="row-block">
            <a class="ControlPanel-title" href="free_delivery">{% translate "free delivery" %}</a>
          </div>
          <div class="row-block hide_700">
            <span class="ControlPanel-title">{% translate "follow us" %}</span>
            <ul class="menu menu_img menu_smallImg ControlPanel-menu">
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialHeader/fb.svg' %}" alt="fb.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <nav class="row-block">
        <div class="row ControlPanel-rowSplit">
          <div class="row-block">{% get_current_language as LANGUAGE_CODE %}
            <form class="ControlPanel-title" action="{% url 'set_language' %}" method="post">
              {% if LANGUAGE_CODE == 'ru' %}
                  {% csrf_token %}
                  <input name="language" type="hidden" value="en-us" />
                  <button class="ControlPanel-title link padding-0" type="submit" value="en-us">en</button>
              {% else %}
                  {% csrf_token %}
                  <input name="language" type="hidden" value="ru" />
                  <button class="ControlPanel-title link padding-0" type="submit" value="ru">ру</button>
              {% endif %}
            </form>
            <span class="ControlPanel-title"> / </span>
            {% if user.is_authenticated %}
            <a class="ControlPanel-title" href="{% url 'user:user_account' request.user.id %}">
              {% translate "account"|capfirst %}
            </a>
            <span class="ControlPanel-title"> / </span>
            <a id="logout-btn" class="ControlPanel-title" href="{% url 'user:logout' %}">
              {% translate "log out" %}
            </a>
            {% else %}
            <button id="login_btn" class="ControlPanel-title link">{% translate "login" %}</button>
            <span class="ControlPanel-title"> / </span>
            <button id="sign_up_btn" class="ControlPanel-title link">{% translate "register" %}</button>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>
<div class="wrap">
  <div class="row Header-rowMain">
    <div class="row-block Header-logo">
      <a class="logo" href="{% url 'product:home' %}">
        <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/>
      </a>
    </div>
    <nav class="row-block row-block_right Header-menu">
      <div class="menuModal" id="navigate">
        <ul class="menu menu_main">
          <li class="menu-item">
            <a class="menu-link" href="{% url 'product:home' %}">{% translate "home" %}</a>
          </li>
          <li class="menu-item">
            <span class="menu-label menu-label_danger">{% translate "new" %}</span>
            <a class="menu-link" href="{% url 'product:list' %}">{% translate "catalog" %}</a>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:list' %}">{% translate "shops" %}</a>
          </li>
          <li class="menu-item">
            <span class="menu-label menu-label_success">{% translate "hot" %}</span>
            <a class="menu-link" href="{% url 'discount:list' %}">{% translate "discounts" %}</a>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="{% url 'shop:contacts_detail' %}">{% translate "contacts" %}</a>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="{% url 'info:about' %}">{% translate "about" %}</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="row-block">
      <div class="CartBlock">
        
        <a class="CartBlock-block" href="{% url 'user:compare_list' pk=0 %}">
          <img class="CartBlock-img" src="{% static 'assets/img/icons/exchange.svg' %}" alt="exchange.svg"/>
          <span id="Compare-amount" class="CartBlock-amount">{% head_count request=request %}</span>
        </a>
        

        {% with qty=cart|length %}
          <a class="CartBlock-block" href="{% url 'order:cart' %}">
            <img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="cart.svg"/>
            <span id="CartBlock-amount" class="CartBlock-amount">{{ qty }}</span>
          </a>
        {% endwith %}

        {% with price=cart.get_min_sum %}
          <div class="CartBlock-block">
            <span id="CartBlock-price" class="CartBlock-price">{{ price }}$</span>
          </div>
        {% endwith %}

      </div>
    </div>
    <div class="row-block Header-trigger">
      <a class="menuTrigger" href="#navigate">
        <div class="menuTrigger-content">{% translate "show navigation"|capfirst %}</div>
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
  </div>
</div>
<div class="Header-searchWrap">
  <div class="wrap">
    <div class="Header-categories">
      <div class="CategoriesButton">
        <div class="CategoriesButton-title">
          <div class="CategoriesButton-icon">
            <img src="{% static 'assets/img/icons/allDep.svg' %}" alt="allDep.svg"/>
          </div>
          <span class="CategoriesButton-text">{% translate "all departments" %}</span>
          <div class="CategoriesButton-arrow"></div>
        </div>

        <div class="CategoriesButton-content">
        {% for category in categories.values %}
          <div class="CategoriesButton-link">
            <a href="/catalog/?category={{ category.object.id }}">
              <div class="CategoriesButton-icon">
                <img src="{{ category.object.icon.url }}" alt=""/>
              </div>
              <span class="CategoriesButton-text">
                {% comment %} {% blocktrans %} {% endcomment %}
                {{ category.object.title }}
                {% comment %} {% endblocktrans %} {% endcomment %}
              </span>
            </a>
            {% if category.childs %}
            <a class="CategoriesButton-arrow" href="/catalog/?category={{ category.object.id }}"></a>
            <div class="CategoriesButton-submenu">
              {% for subcategory in category.childs %}
                <a class="CategoriesButton-link" href="/catalog/?category={{ subcategory.id }}">
                  <div class="CategoriesButton-icon">
                      <img src="{{ subcategory.icon.url }}" alt=""/>
                  </div>
                  <span class="CategoriesButton-text">
                    {% comment %} {% blocktrans %} {% endcomment %}
                    {{ subcategory.title }}
                    {% comment %} {% endblocktrans %} {% endcomment %}
                  </span>
                </a>
              {% endfor %}
              </div>
            {% endif %}
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
    <div class="Header-searchLink">
      <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
    </div>
    <div class="Header-search">
      <div class="search">
        <form class="form form_search" action="/catalog/" method="post">
          {% csrf_token %}
          <input class="search-input" id="query" name="query" type="text" value="{% if query %}{{ query }}{% endif %}" placeholder="{% translate 'What are you looking for ...' %}"/>
          <button class="search-button" type="submit" name="submit" id="search">
            <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>{% translate "search"|capfirst %}
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

marketplace_app/templates/scripts.html
{% load static %}
<script src="{% static 'assets/js/jquery-3.2.1.min.js' %}">
</script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}">
</script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}">
</script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}">
</script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}">
</script>
<script src="{% static 'assets/js/alertify.min.js' %}">
</script>
<script src="{% static 'assets/js/scripts.js' %}">
</script>
<script src="{% static 'assets/js/bootstrap.min.js' %}">
</script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}">
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#login_btn").modalForm({
                formURL: "{% url 'user:login' %}"
              });
    });
    $(document).ready(function() {
        $("#login_btn_reset").modalForm({
                formURL: "{% url 'user:login' %}"
              });
    });


    $(document).ready(function() {
        $("#order-login-btn").modalForm({
                formURL: `{% url 'user:login' %}?next=${window.location.pathname}`
              });
    });


    $(document).ready(function() {
        $("#sign_up_btn").modalForm({
                formURL: "{% url 'user:signup' %}"
              });
    });
</script>

<script src="{% static 'js/jquery.inputmask.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $(".phone").inputmask("+7 (999) 999-99-99");
});
</script>