marketplace_app/info/urls.py
"""marketplace_app.info URL Configuration
"""
from django.urls import path
from .views import AboutView

app_name = "info"

urlpatterns = [
    path("about/", AboutView.as_view(), name="about"),
]

marketplace_app/marketplace_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("", include("user.urls", namespace="user")),
    path("", include("shop.urls", namespace="shop")),
    path("", include("order.urls", namespace="order")),
    path("", include("discount.urls", namespace="discount")),
    path("", include("info.urls", namespace="info")),
    path("", include("django.contrib.auth.urls")),
]

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:

    urlpatterns = [
        # path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace_app/order/urls.py
"""marketplace_app.order URL Configuration
"""
from django.urls import path

from order import views

app_name = "order"

order_forms = getattr(views.OrderView, "order_forms", list())

urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/<int:pk>", views.AddToCartView.as_view(), name="add-to-cart"),
    path(
        "cart/add/<int:pk>/<int:cnt>",
        views.AddToCartView.as_view(),
        name="add-to-cart-cnt",
    ),
    path(
        "cart/add/<int:pk>/shop/<int:shop_id>",
        views.AddToCartView.as_view(),
        name="add-to-cart-shop",
    ),
    path(
        "cart/remove/<int:pk>",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
    path("order/<int:pk>/", views.OrderDetail.as_view(), name="order-detail"),
    path(
        "order/",
        views.OrderView.as_view(order_forms),
        name="order",
    ),
    path("order/<int:pk>/payment/", views.PaymentView.as_view(), name="payment"),
]

marketplace_app/product/urls.py
"""marketplace_app.product URL Configuration
"""
from django.urls import path
from product.views import IndexView, ProductListView, ProductDetailView

app_name = "product"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("catalog/", ProductListView.as_view(), name="list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="detail"),
]

marketplace_app/shop/urls.py
from django.urls import path

from .views import ContactsView, ShopDetailView, ShopListView


app_name = "shop"

urlpatterns = [
    path("contacts/", ContactsView.as_view(), name="contacts_detail"),
    path("shops/", ShopListView.as_view(), name="list"),
    path("shops/<int:pk>/", ShopDetailView.as_view(), name="detail"),
]

marketplace_app/user/urls.py
"""marketplace_app.user URL Configuration
"""
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from user import views

app_name = "user"

urlpatterns = [
    path("user/<int:pk>/account/", views.UserAccount.as_view(), name="user_account"),
    path("user/<int:pk>/profile/", views.UserProfile.as_view(), name="user_profile"),
    path(
        "user/<int:pk>/orders/", views.HistoryOrders.as_view(), name="user_orders_list"
    ),
    path("user/<int:pk>/views/", views.HistoryViews.as_view(), name="user_views"),
    path(
        "compare/category/<int:pk>/",
        views.CompareProduct.as_view(),
        name="compare_list",
    ),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password_reset/",
        views.PasswordResetViewCustom.as_view(),
        name="password_reset",
    ),
]

marketplace_app/order/forms.py
from functools import cached_property

from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils.translation import gettext as _

from order import models as order_models
from order.utils import db_table_exists
from user import models as user_models
from user.forms import CustomUserAddForm


class UserInfoFormAnonymous(CustomUserAddForm):
    full_name = forms.CharField()

    class Meta:
        model = user_models.CustomUser
        fields = [
            "full_name",
            "phone",
            "email",
            "password1",
            "password2",
        ]


def validate_char_fields(value):
    """Валидация текстовый полей"""
    if not any(char.isalpha() for char in value):
        raise ValidationError(
            _("%(value)s is incorrect"),
            params={"value": value},
        )


class UserInfoForm(forms.Form):
    """Форма информации о пользователе при оформлении заказа"""

    full_name = forms.CharField(
        validators=[
            validate_char_fields,
        ],
        required=False,
    )
    phone = forms.CharField(
        validators=[
            user_models.CustomUser.phone_regex,
        ],
        required=False,
    )
    email = forms.EmailField(
        validators=[
            validate_email,
        ],
        required=False,
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
        required=False,
    )


class DeliveryTypeChoices:
    """Варианты типа доставки при оформлении заказа"""

    # TODO костыль для миграций, джанго очень не любит подобные обращения в таблицу из модулей
    @db_table_exists("order_deliverytype")
    def get_choices(self) -> list:
        delivery_types = order_models.DeliveryType.objects.all()
        return [
            (
                str(delivery.id),
                delivery.name,
            )
            for delivery in delivery_types
        ]

    @cached_property
    def choices(self):
        return self.get_choices()


class DeliveryForm(forms.Form):
    """Форма доставки при оформлении заказа"""

    delivery_type = forms.ChoiceField(choices=DeliveryTypeChoices().choices)
    city = forms.CharField(
        validators=[
            validate_char_fields,
        ],
        required=False,
    )
    address = forms.CharField(
        validators=[
            validate_char_fields,
        ],
        required=False,
    )


class PaymentForm(forms.Form):
    """Форма платежа при оформлении заказа"""

    payment_types = order_models.Order.PaymentType.choices
    payment_type = forms.ChoiceField(choices=payment_types)

marketplace_app/payments/forms.py
from django import forms

from .models import Payment


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ["card"]
        widgets = {
            "card": forms.TextInput(
                attrs={
                    "class": "form-input Payment-bill",
                    "type": "text",
                    "placeholder": "9999 9999",
                    "data-mask": "9999 9999",
                    "data-validate": "require pay",
                }
            )
        }

    def clean(self):
        card = self.cleaned_data["card"]
        print(card)
        super().clean()

marketplace_app/order/views.py
import json
import random
import typing
from collections import OrderedDict

from django import views
from django.core.handlers.wsgi import WSGIRequest
from django.forms import forms
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from formtools.wizard.views import SessionWizardView

from order.mixins import CartMixin, cart_init_data
from order import forms as order_forms
from order import models as order_models
from order.utils import WRONG_REQUEST
from payments.models import Payment
from payments.forms import PaymentForm

from user import models as user_models


class CartView(CartMixin):
    """Вью Корзины"""

    def post(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """
        Обработка POST запроса:
        от клиента получаем идентификаторы и флаги
        для последующей обработки запроса
        """
        self.cart = self.get_queryset()
        stock_id = request.POST.get("stock_id")
        quantity = request.POST.get("quantity")
        shop_id = request.POST.get("shop_id")

        message = WRONG_REQUEST
        success = False

        if stock_id:
            if quantity:
                success, message = self.cart.update_quantity(
                    stock_id=stock_id, quantity=int(quantity)
                )
            elif shop_id:
                success, message = self.cart.change_shop_by_id(
                    stock_id=stock_id, shop_id=shop_id
                )

        response_data = self.prepare_response_data(
            success=success,
            message=message.capitalize(),
            cart_count=self.cart.count,
            price=self.cart.get_min_sum(),
        )
        return HttpResponse(
            json.dumps(response_data, default=str), content_type="application/json"
        )

    def get(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """Возвращаем список элементов корзины и их стоимость"""
        self.cart = self.get_queryset()

        return render(
            request,
            template_name=self.template_name,
            context={"cart": self.cart, "total": self.get_sum()},
        )

    def get_queryset(self) -> order_models.Cart:
        """Получение объекта корзины по id"""
        # TODO добавить only
        cart_pk = self.get_cart_pk()
        return (
            self.model.objects.prefetch_related("cart_entity")
            .prefetch_related("cart_entity__stock__product")
            .prefetch_related("cart_entity__stock__shop")
            .filter(id=cart_pk)
            .first()
        )

    def get_sum(self) -> dict:
        """Получение цены продукта"""
        return self.cart.total_sums()


class AddToCartView(CartMixin):
    """Вью добавления в корзину"""

    @staticmethod
    def random_choice(values: list) -> typing.Any:
        """Рандомизируем продавца товара при добавлении в корзину согласно ТЗ"""
        return random.choice(values)

    def post(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """
        Обработка POST запроса:
        от клиента получаем идентификаторы и флаги
        для последующей обработки запроса

        :return - json с количеством товаров в корзине и минимальной стоимостью
        """
        pk = kwargs.get("pk")
        shop = kwargs.get("shop_id")
        cnt = kwargs.get("cnt", 1)
        cart = self.get_cart()
        is_product = request.POST.get("is_product", None)
        if shop is not None:
            stock_id = shop
        elif is_product:
            stocks = self.stock_model.objects.filter(product__id=pk)
            stock_ids = stocks.values_list("id", flat=True)
            stock_id = self.random_choice(stock_ids)
        else:
            stock_id = pk

        success, message = cart.add_to_cart(stock_id=stock_id, cnt=int(cnt))
        response_data = self.prepare_response_data(
            success=success,
            message=message.capitalize(),
            cart_count=cart.count,
            price=cart.get_min_sum(),
        )
        return HttpResponse(
            json.dumps(response_data, default=str),
            content_type="application/json",
            status=200,
        )


class RemoveFromCartView(CartMixin):
    """Вью удаления из корзины"""

    def delete(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """Удаляем товар по id из kwargs"""
        stock_id = kwargs.get("pk")
        cart = self.get_cart()
        success, message = cart.remove_from_cart(stock_id=stock_id)
        response_data = self.prepare_response_data(
            success=success,
            message=message.capitalize(),
            cart_count=cart.count,
            price=cart.get_min_sum(),
        )
        return HttpResponse(
            json.dumps(response_data, default=str), content_type="application/json"
        )


class OrderDetail(generic.DetailView):
    """
    Представление страницы oneorder.html

    - детальная информация заказа
    - возможность оплатить заказ, если не оплачен
    """

    model = order_models.Order
    template_name = "order/oneorder.html"
    context_object_name = "order"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if not obj.user_id == self.request.user and not self.request.user.is_superuser:
            raise Http404

        return obj

    def get_context_data(self, **kwargs):
        kwargs.setdefault("view", self)
        kwargs.update({"order": self.get_object()})
        kwargs.update(
            {"payment": Payment.objects.filter(order=self.get_object()).first()}
        )

        return kwargs


class OrderView(SessionWizardView):
    """Вью оформления заказа"""

    confirm_step = "confirm"
    confirm_step_index = 3
    confirm_template = f"order/forms/{confirm_step}.html"

    done_step = "done"
    done_step_index = 4

    cart_model = order_models.Cart
    delivery_model = order_models.Delivery
    order_model = order_models.Order
    order_entity_model = order_models.OrderEntity
    user_model = user_models.CustomUser

    delivery_form_key = "delivery_form"
    payment_form_key = "payment_form"
    user_info_form_key = "user_info_form"

    cart_key = "cart"
    cart_sum_key = "cart_sum"
    delivery_sum_key = "delivery_sum"
    total_sum_key = "total_sum"

    order_forms = (
        (
            user_info_form_key,
            order_forms.UserInfoForm,
        ),
        (
            delivery_form_key,
            order_forms.DeliveryForm,
        ),
        (
            payment_form_key,
            order_forms.PaymentForm,
        ),
    )
    order_forms_templates = {
        user_info_form_key: f"order/forms/{user_info_form_key}.html",
        delivery_form_key: f"order/forms/{delivery_form_key}.html",
        payment_form_key: f"order/forms/{payment_form_key}.html",
    }

    def get_user_data(self) -> dict:
        """Получаем данные формы авторизованного пользователя"""
        user_data = {}
        user_attrs = [
            "full_name",
            "email",
            "phone",
        ]
        user = self.request.user
        for attr in user_attrs:
            user_data.update({f"{attr}": getattr(user, attr, None)})
        return OrderedDict(user_data)

    def get(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """Рендер формы по параметру или первого шага"""
        self.storage.current_step = self.steps.first
        user = getattr(request, "user", None)
        data = self.get_user_data() if user.is_authenticated else {}
        data = OrderedDict(data)
        form = self.get_form(data=data)
        return self.render(form)

    def get_template_names(self):
        """Получение шаблона для конкретного шага"""
        return [self.order_forms_templates[self.steps.current]]

    def handle_user(self, user_form: forms.BaseForm) -> forms.BaseForm:
        """Постобработка данных анонимного пользователя"""
        user = user_form.save()
        user_name_data = self.user_model.parse_user_name(
            user_form.cleaned_data.pop("full_name", dict())
        )
        for attr, value in user_name_data.items():
            setattr(user, attr, value)
        user.save(update_fields=user_name_data.keys())

        self.user_model.login_new_user(
            request=self.request,
            email=user_form.cleaned_data["email"],
            password=user_form.cleaned_data["password1"],
        )
        return user_form

    def user_info_form_handler(self, form: forms.BaseForm) -> forms.BaseForm:
        """Обработчик формы информации о пользователе"""
        if self.request.user.is_anonymous:
            user_creation_form = order_forms.UserInfoFormAnonymous(
                data=form.cleaned_data
            )
            if user_creation_form.is_valid():
                self.handle_user(user_creation_form)
            else:
                return user_creation_form
        return form

    def get_step_index(self, step: str = None) -> int:
        """Получаем индекс шага"""
        index = super().get_step_index(step)
        if index is None and step in (self.confirm_step, self.done_step):
            return (
                self.confirm_step_index
                if step == self.confirm_step
                else self.done_step_index
            )
        return index

    def get_step_number(self, step: str = None) -> int:
        """Получаем номер шага"""
        index = self.get_step_index(step)
        if index:
            return index + 1

    def handle_form(self, form: forms.BaseForm) -> forms.BaseForm:
        """Общий обработчик форм"""
        if isinstance(form, order_forms.UserInfoForm):
            form = self.user_info_form_handler(form)
        return form

    def store_form_data(self, form: forms.BaseForm) -> None:
        """Сохранение данных формы в сессию"""

marketplace_app/order/templates/order/cart.html
{% extends "base.html" %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block title %}
  {{seo.title}}
{% endblock %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% translate "cart" %}
        </h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% translate "home" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{% translate "cart" %}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section">
    <div class="wrap">
      {% if cart|length %}
        <form class="form Cart" action="#" method="post">

        {% for cart_entity in cart.cart_entity.all %}
          <div class="Cart-product">

          <div class="Cart-block Cart-block_row">
            <div class="Cart-block Cart-block_pict">
              <a class="Cart-pict" href="{% url 'product:detail' cart_entity.stock.product.id %}">
                <img class="Cart-img" src="{{ cart_entity.stock.product.image.url }}" alt="card.jpg"/>
              </a>
            </div>
            <div class="Cart-block Cart-block_info">
              <a class="Cart-title" href="{% url 'product:detail' cart_entity.stock.product.id %}">{{ cart_entity.stock.product.title }}</a>
              <div class="Cart-desc">{{ cart_entity.stock.product.short_description }}</div>
              <div class="Cart-quantity">{% translate "in stock"|capfirst %}: {{ cart_entity.stock.count }}</div>
            </div>
            <div class="Cart-block Cart-block_price">
              {% comment %} {% if cart_entity.stock.product.discount.type %} {% endcomment %}
                {% comment %} <div class="Cart-price Cart-price_old">{{ cart_entity.stock.price }}$ {% endcomment %}
                {% comment %} </div> {% endcomment %}

                {% comment %} <div class="Cart-price">{{ cart_entity.stock.product.discount.price }}$ {% endcomment %}
                {% comment %} </div> {% endcomment %}
              {% comment %} {% else %} {% endcomment %}
                <div class="Cart-price">{{ cart_entity.stock.price }}$</div>
              {% comment %} {% endif %} {% endcomment %}
            </div>
          </div>
          <div class="Cart-block Cart-block_row">
            <div class="Cart-block Cart-block_seller">
              <select class="form-select">
                {% for shop in cart_entity.stock.product.get_shops %}
                  {% if cart_entity.stock.shop.id == shop.id %}
                    <option value="{{ shop.id }}" selected="selected" class="Cart-block-seller-option">
                      {{ shop.name }}
                    </option>
                  {% else %}
                    <option value="{{ shop.id }}" class="Cart-block-seller-option">
                      {{ shop.name }}
                    </option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
            <div class="Cart-block Cart-block_amount">
              <div class="Cart-amount">
                <div class="Amount">
                  <button class="Amount-remove" value="{{ cart_entity.stock.id }}" type="button" href="{% url 'order:cart' %}" ></button>
                  <input class="Amount-input form-input" name="amount" type="text" value="{{ cart_entity.quantity }}" max="{{ cart_entity.stock.count }}"/>
                  <button class="Amount-add" value="{{ cart_entity.stock.id }}" type="button" href="{% url 'order:cart' %}"></button>
                </div>
              </div>
            </div>
            <div class="Cart-block Cart-block_delete">
              <a class="Cart-delete" href="{% url 'order:remove-from-cart' cart_entity.stock.id %}">
                <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}

        <div class="Cart-total">
          <div class="Cart-block Cart-block_total">
            <strong class="Cart-title">{% trans "total"|capfirst %}:</strong>
            {% if total.discount_sum %}
            <span class="Cart-price">{{ total.discount_sum }}$</span><span class="Cart-price_old">{{ total.old_sum }}$</span>
            {% else %}
            <span class="Cart-price">{{ total.old_sum }}$</span>
            {% endif %}
          </div>

        <div class="Cart-block">
          <a class="btn btn_success btn_lg" href="{%  url 'order:order' %}">{% trans 'place order' %}</a>
        </div>

      </div>

      </form>
      {% else %}
      <div class="empty-cart">
        {% trans 'Cart is empty :(' %}
      </div>

      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

marketplace_app/order/templates/order/oneorder.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load order_tags %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% trans "order" %} №{{ order.id }}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% trans "home" %}</a>
          </li>
          <li class="breadcrumbs-item">
            <a href="{% url 'user:user_orders_list' pk=user.pk %}">{% trans "order history"|capfirst %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{% trans "order"|capfirst %} №{{ order.id }}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section">
    <div class="wrap">
      <div class="Section-content">
        <div class="Orders"></div>
        <div class="Order">
          <div class="Order-infoBlock">
            <div class="Order-personal">
              <div class="row">
                <div class="row-block">
                  <div class="Order-info Order-info_date">
                    <div class="Order-infoType">{% trans "order date"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.datetime|date:"d.m.y" }}</div>
                  </div>
                  {% with order.user_id as user %}
                  <div class="Order-info">
                    <div class="Order-infoType">{% trans "full name"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ user.get_full_name }}</div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">{% trans "phone"|capfirst %}:</div>
                    {% phone_normalize phone=user.phone as phone %}
                    <div class="Order-infoContent">{{ phone }}</div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">{% trans "e-mail"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ user.email }}</div>
                    {% endwith %}
                  </div>
                </div>
                <div class="row-block">
                  <div class="Order-info Order-info_delivery">
                    <div class="Order-infoType">{% trans "type delivery"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.delivery_id.delivery_type }}</div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">{% trans "city"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.delivery_id.city }}</div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">{% trans "address"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.delivery_id.address }}</div>
                  </div>
                  <div class="Order-info Order-info_pay">
                    <div class="Order-infoType">{% trans "payment"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.get_payment_type_display }}</div>
                  </div>
                  <div class="Order-info Order-info_status">
                    <div class="Order-infoType">{% trans "status"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.get_state_display }}</div>
                  </div>
                  {% if order.error %}
                  <div class="Order-info Order-info_error">
                    <div class="Order-infoType">{% trans "payment failed"|capfirst %}:</div>
                    <div class="Order-infoContent">{{ order.get_error_display }}</div>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="Cart Cart_order">
              {% with order.get_order_entity as entity_list %}
              {% if entity_list %}
              {% for entity in entity_list %}
              {% with entity.stock_id.product as product %}
              <div class="Cart-product">
                {% url 'product:detail' product.id as product_url %}
                <div class="Cart-block Cart-block_row">
                  <div class="Cart-block Cart-block_pict">
                    <a class="Cart-pict" href="{{ product_url }}">
                      {% if product.image %}
                      <img class="Cart-img" src="{{ product.image.url }}" alt="card.jpg"/>
                      {% else %}
                      <img class="Cart-img" src="{% static 'assets/img/content/home/card.jpg' %}" alt="card.jpg"/>
                      {% endif %}
                    </a>
                  </div>
                  <div class="Cart-block Cart-block_info">
                    <a class="Cart-title" href="{{ product_url }}">{{ product.title }}</a>
                    <div class="Cart-desc">{{ product.short_description }}</div>
                  </div>
                  <div class="Cart-block Cart-block_price">
                    {% if entity.discounted_price %}
                    <div class="Cart-price">{{ entity.discounted_price }}$</div>
                    {% else %}
                    <div class="Cart-price">{{ entity.price }}$</div>
                    {% endif %}
                  </div>
                </div>
                <div class="Cart-block Cart-block_row">
                  <div class="Cart-block Cart-block_seller">
                    <div>{% trans "shop"|capfirst %}:</div>
                    <div>{{ entity.stock_id.shop }}</div>
                  </div>
                  <div class="Cart-block Cart-block_amount">{{ entity.count }} {% trans "pc." %}</div>
                </div>
              </div>
              {% endwith %}
              {% endfor %}
              {% endif %}
              {% endwith %}
              
              <div class="Cart-total">
                <div class="Cart-block Cart-block_total">
                  <div>
                    <span class="Cart-block Cart-block_amount">{% trans 'delivery'|capfirst %}: {{ order.delivery_id.price }}$</span>
                  </div>
                  <strong class="Cart-title">
                    {% trans "total"|capfirst %}:
                    {% with order.discounted_sum_order as discounted_sum_order and order.sum_order as sum_order %}
                    {% if discounted_sum_order == sum_order %}
                      <span class="Cart-price">{{ sum_order }}$</span>
                    {% else %}
                      <span class="Cart-price">{{ discounted_sum_order }}$</span>
                      <span class="Cart-price_old">{{ sum_order }}$</span>
                    {% endif %}
                    {% endwith %}
                  </strong>
                </div>
                {% if order.state == 'not paid' %}
                <div class="Cart-block">
                  <a class="btn btn_primary btn_lg btn_success" href="#">{% trans "to pay"|capfirst %}</a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}