marketplace_app/info/urls.py
"""marketplace_app.info URL Configuration
"""
from django.urls import path
from .views import AboutView

app_name = "info"

urlpatterns = [
    path("about/", AboutView.as_view(), name="about"),
]

marketplace_app/marketplace_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("", include("user.urls", namespace="user")),
    path("", include("shop.urls", namespace="shop")),
    path("", include("order.urls", namespace="order")),
    path("", include("discount.urls", namespace="discount")),
    path("", include("info.urls", namespace="info")),
    path("", include("django.contrib.auth.urls")),
]

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:

    urlpatterns = [
        # path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace_app/order/urls.py
"""marketplace_app.order URL Configuration
"""
from django.urls import path

from order import views

app_name = "order"

order_forms = getattr(views.OrderView, "order_forms", list())

urlpatterns = [
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/<int:pk>", views.AddToCartView.as_view(), name="add-to-cart"),
    path(
        "cart/add/<int:pk>/<int:cnt>",
        views.AddToCartView.as_view(),
        name="add-to-cart-cnt",
    ),
    path(
        "cart/add/<int:pk>/shop/<int:shop_id>",
        views.AddToCartView.as_view(),
        name="add-to-cart-shop",
    ),
    path(
        "cart/remove/<int:pk>",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
    path("order/<int:pk>/", views.OrderDetail.as_view(), name="order-detail"),
    path(
        "order/",
        views.OrderView.as_view(order_forms),
        name="order",
    ),
    path("order/<int:pk>/payment/", views.PaymentView.as_view(), name="payment"),
]

marketplace_app/product/urls.py
"""marketplace_app.product URL Configuration
"""
from django.urls import path
from product.views import IndexView, ProductListView, ProductDetailView

app_name = "product"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("catalog/", ProductListView.as_view(), name="list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="detail"),
]

marketplace_app/user/urls.py
"""marketplace_app.user URL Configuration
"""
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from user import views

app_name = "user"

urlpatterns = [
    path("user/<int:pk>/account/", views.UserAccount.as_view(), name="user_account"),
    path("user/<int:pk>/profile/", views.UserProfile.as_view(), name="user_profile"),
    path(
        "user/<int:pk>/orders/", views.HistoryOrders.as_view(), name="user_orders_list"
    ),
    path("user/<int:pk>/views/", views.HistoryViews.as_view(), name="user_views"),
    path(
        "compare/category/<int:pk>/",
        views.CompareProduct.as_view(),
        name="compare_list",
    ),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password_reset/",
        views.PasswordResetViewCustom.as_view(),
        name="password_reset",
    ),
]

marketplace_app/user/views.py
import json

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views import generic

from order.models import Order
from payments.models import Payment
from product.models import AttributeValue
from user.forms import (
    UserProfileForm,
    CustomAuthenticationForm,
    CustomUserCreationForm,
    PasswordResetCustomForm,
)
from user.mixin import ResponseDataMixin
from user.models import CustomUser, UserProductView, Compare
from user.utils import full_name_analysis

from bootstrap_modal_forms.generic import BSModalLoginView, BSModalCreateView


class UserAccount(LoginRequiredMixin, generic.DetailView):
    """
    Представление страницы account.html

    - информация о пользователе;
    - информация о последнем заказе;
    - последние просмотренные товары
    """

    model = CustomUser
    template_name = "user/account.html"
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_active"] = "account_active"
        context["last_order"] = Order.get_last_order(user=self.request.user)
        context["product_view"] = UserProductView.get_product_view(
            user=self.request.user, limit=3
        )
        context["payment"] = Payment.objects.filter(order=context["last_order"])
        return context


class UserProfile(LoginRequiredMixin, generic.UpdateView):
    """
    Представление страницы profile.html

    - форма для редактирования данных пользователя
    """

    model = CustomUser
    form_class = UserProfileForm
    template_name = "user/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_active"] = "profile_active"
        return context

    def get_form_kwargs(self):
        kwargs = super(UserProfile, self).get_form_kwargs()
        kwargs.update(
            {
                "initial": {
                    "full_name": self.request.user.get_full_name,
                }
            }
        )
        return kwargs

    def form_valid(self, form):
        user = form.save(commit=False)

        if self.request.FILES:
            avatar = self.request.FILES["avatar"]
            if avatar.size > 2 * 1024 * 1024:
                messages.error(
                    self.request,
                    _("Image file too large ( > 2mb )"),
                    extra_tags="error",
                )
                return HttpResponseRedirect(
                    reverse("user:user_profile", kwargs={"pk": user.pk})
                )
            user.avatar = avatar
        else:
            avatar = self.request.user.avatar
            user.avatar = avatar

        full_name = form.cleaned_data.get("full_name")
        password = form.cleaned_data.get("password1")
        if full_name:
            user_name_data = full_name_analysis(full_name=full_name)
            user.last_name = user_name_data["last_name"]
            user.first_name = user_name_data["first_name"]
            user.middle_name = user_name_data["middle_name"]
        else:
            user.last_name = ""
            user.first_name = ""
            user.middle_name = ""

        if password:
            user.set_password(password)

        user.save()
        login(self.request, user)
        messages_text = _("Profile saved successfully")
        messages.success(self.request, messages_text, extra_tags="success")

        return HttpResponseRedirect(
            reverse("user:user_profile", kwargs={"pk": user.pk})
        )


class HistoryOrders(LoginRequiredMixin, generic.ListView):
    """
    Представление страницы historyorder.html

    - список заказов пользователя
    """

    model = Order
    template_name = "user/historyorder.html"
    context_object_name = "orders_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_active"] = "historyorder_active"
        return context

    def get_queryset(self):
        orders_list = Order.objects.filter(user_id=self.request.user)
        return orders_list


class HistoryViews(LoginRequiredMixin, ResponseDataMixin, generic.ListView):
    """
    Представление страницы historyview.html

    - список просмотренных товаров,
    ограничен 20 последними просмотрами
    """

    model = UserProductView
    template_name = "user/historyview.html"
    context_object_name = "views_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_active"] = "historyview_active"
        return context

    def get_queryset(self):
        views_list = UserProductView.get_product_view(user=self.request.user, limit=20)
        return views_list

    def post(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """
        Обработка POST запроса:
        от клиента получаем идентификаторы и флаги
        для последующей обработки запроса
        """

        product_id = kwargs["pk"]
        success, message = UserProductView.add_object(
            user=self.request.user, product=product_id
        )

        response_data = self.prepare_response_data(
            success=success, message=message.capitalize()
        )

        return HttpResponse(
            json.dumps(response_data, default=str), content_type="application/json"
        )


class CompareProduct(ResponseDataMixin, generic.ListView):
    """
    Представление страницы compare.html

    - список товаров для сравнения,
    ограничен 4 товарами
    """

    model = Compare
    template_name = "user/compare.html"
    context_object_name = "compare_list"

    def get_context_data(self, **kwargs):
        compare = Compare.get_compare(self.request)

        context = super().get_context_data(**kwargs)
        context["categories"] = Compare.get_categories(compare_id=compare)
        if self.kwargs["pk"] == 0:
            context["cat_selected"] = 0
        else:
            if self.object_list.count() == 0:
                category_id = 0
            else:
                category_id = self.object_list[0].product.category_id
            context["cat_selected"] = category_id
        context["total_count"] = Compare.count(compare_id=compare)

        if self.object_list.count() > 0:
            context["attributes"] = AttributeValue.get_all_attributes_of_product(
                self.object_list[0].product_id
            )

        else:
            messages_text = _("Not enough data to compare")
            messages.success(self.request, messages_text)

        return context

    def get_queryset(self, **kwargs):
        compare = Compare.get_compare(self.request)
        result = Compare.get_compare_list(compare_id=compare.id)
        if self.kwargs["pk"] != 0:
            result = result.filter(product__category=self.kwargs["pk"])

        return result

    def post(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """
        Обработка POST запроса:
        от клиента получаем идентификаторы и флаги
        для последующей обработки запроса
        """

        product_id = kwargs["pk"]
        compare = Compare.get_compare(self.request)
        success, message = compare.add_to_compare(product_id=product_id)
        count = Compare.count(compare_id=compare.id)

        response_data = self.prepare_response_data(
            success=success, message=message.capitalize(), head_count=count
        )

        return HttpResponse(
            json.dumps(response_data, default=str), content_type="application/json"
        )

    def delete(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        """Удаляем товар по id из kwargs"""

        product_id = kwargs["pk"]
        compare = Compare.get_compare(self.request)
        success, message = compare.remove_from_compare(product_id=product_id)
        count = Compare.count(compare_id=compare.id)

        response_data = self.prepare_response_data(
            success=success, message=message.capitalize(), head_count=count
        )

        return HttpResponse(
            json.dumps(response_data, default=str), content_type="application/json"
        )


class CustomLoginView(BSModalLoginView):
    """
    Представление страницы login.html

    - аутентификация пользователя, представляет собой
    всплывающее окно
    """

    authentication_form = CustomAuthenticationForm
    template_name = "user/login.html"
    # success_message = _("Success: You were successfully logged in.")
    success_url = reverse_lazy("product:home")


class SignUpView(BSModalCreateView):
    """
    Представление страницы signup.html

    - регистрация пользователя, представляет собой
    всплывающее окно
    """

    form_class = CustomUserCreationForm
    template_name = "user/signup.html"
    # success_message = _("Success: Sign up succeeded. You can now Log in.")
    success_url = reverse_lazy("product:home")


class PasswordResetViewCustom(PasswordResetView):
    form_class = PasswordResetCustomForm

marketplace_app/user/templates/user/account.html
{% extends "base.html" %}
{% load static %}
{% load l10n %}
{% load i18n %}
{% load category_list %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% trans "account" %}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item"><a href="{% url 'product:home' %}">{% trans "home" %}</a></li>
          <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "account" %}</span></li>
        </ul>
      </div>
    </div>
  </div>  
  <div class="Section Section_column Section_columnLeft">
    <div class="wrap">
      {% include 'user/inc/_navigate_profile.html' %}
      <div class="Section-content">
        <div class="Account">
          <div class="Account-group">
            <div class="Account-column">
              <div class="Account-avatar">
                {% if request.user.avatar %}
                <img src="{{ user.avatar.url }}" alt="card.jpg"/>
                {% else %}
                <img src="{% static 'assets/img/content/home/card.jpg' %}" alt="card.jpg"/>
                {% endif %}
              </div>
            </div>
            <div class="Account-column">
              <div class="Account-name">{{ user.get_full_name }}
              </div><a class="Account-editLink" href="{% url 'user:user_profile' pk=user.id %}">{% trans "edit profile"|capfirst %}</a>
            </div>
          </div>
          <div class="Account-group">
            <div class="Account-column Account-column_full">
              <div class="Order Order_anons">
                <div class="Order-personal">
                  {% if last_order %}
                  <div class="row">
                    <div class="row-block">
                      <a class="Order-title" href="{% url 'order:order-detail' pk=last_order.pk %}">
                        {% trans "order"|capfirst %}&#32;
                        <span class="Order-numberOrder">№{{ last_order.id }}</span>
                        &#32;{% trans "from" %}&#32;
                        <span class="Order-dateOrder">{{ last_order.datetime.date|date:"d.m.Y" }}</span>
                      </a>
                      <div class="Account-editLink">
                        <a href="{% url 'user:user_orders_list' request.user.id %}">{% trans "order history"|capfirst %}</a>
                      </div>
                    </div>
                    <div class="row-block">
                      <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">{% trans "type delivery"|capfirst %}:</div>
                        <div class="Order-infoContent">{{ last_order.delivery_id.delivery_type }}</div>
                      </div>
                      <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">{% trans "payment"|capfirst %}:</div>
                        <div class="Order-infoContent">{{ last_order.get_payment_type_display }}</div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">{% trans "total cost"|capfirst %}:</div>
                        <div class="Order-infoContent">{{ last_order.discounted_sum_order }}$</div> 
                      </div>
                      <div class="Order-info Order-info_status">
                        <div class="Order-infoType">{% trans "status"|capfirst %}:</div>
                        <div class="Order-infoContent">{{ last_order.get_state_display }}</div>
                      </div>
                      {% if last_order.error %}
                      <div class="Order-info Order-info_error">
                        <div class="Order-infoType">{% trans "payment failed"|capfirst %}:</div>
                        <div class="Order-infoContent">{{ last_order.get_error_display }}</div>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  {% else %}
                  <div class="row-block">{% trans "You don't have any orders" %}</div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <div class="Account-group">
            <div class="Account-column Account-column_full">
              <header class="Section-header">
                <h2 class="Section-title">{% trans "viewing history"|capfirst %}</h2>
              </header>
              {% if product_view %}
              <div class="Cards Cards_account">
                {% if product_view.0 %}
                  {% with product_view.0.product_id as product %}
                  
                  <div class="Card">
                    {% include "card.html" %}
                  </div>
                  {% endwith %}
                {% endif %}
                {% if product_view.1 %}
                  {% with product_view.1.product_id as product %}
                  
                  <div class="Card hide_700">
                    {% include "card.html" %}
                  </div>
                  {% endwith %}
                {% endif %}
                {% if product_view.2 %}
                  {% with product_view.2.product_id as product %}
                  
                  <div class="Card hide_md">
                    {% include "card.html" %}
                  </div>
                  {% endwith %}
                {% endif %}
              </div>
              <div class="Account-editLink Account-editLink_view">
                <a href="{% url 'user:user_views' request.user.id %}">{% trans "Go to the full list" %}</a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

marketplace_app/user/templates/user/compare.html
{% extends "base.html" %}
{% load static %}
{% load l10n %}
{% load i18n %}
{% load user_tags %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% trans "comparison of products" %}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% trans "home" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            {% trans "comparison of products" %}<span></span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section">
    <div class="wrap">
      <article class="Article">
        <p>
          {% trans 'Diverse and rich experience, constant quantitative growth and the scope of our activity provides a wide range of (specialists) participation in the formation of the personnel training system, meets the urgent needs. Ideological considerations of the highest order, as well as consultation with a broad asset, require the definition and clarification of the appropriate activation conditions.' %}
        </p>
      </article>
      
      <div class="Compare">
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li class="Compare-message">
              {{ message|safe }}
            </li>
          {% endfor %}
        </ul>
        {% endif %}

        {% with compare_list as compare %}
        {% if compare %}
        {% if categories|length > 1 %}
        <div class="Compare-categories Compare-row">
          <div class="Compare-category">
            {% if cat_selected == 0 %}
              <p class="selected">{% trans 'all'|upper %} <span>{{ total_count }}</span></p>
            {% else %}
              <a href="{% url 'user:compare_list' pk=0 %}">{% trans 'all'|upper %} <span>{{ total_count }}</span></a>
            {% endif %}
          </div>

          {% for category, count in categories.items %}
          <div class="Compare-category">
            {% if category.pk == cat_selected %}
            <p class="selected">
              {% if category.parent %} 
              {{ category.title|upper }} 
              {% else %} 
              {{ category|upper }} 
              {% endif %} 
              <span>{{ count }}</span>
            </p>
            {% else %}
            <a href="{% url 'user:compare_list' pk=category.pk %}">
              {% if category.parent %} 
              {{ category.title|upper }} 
              {% else %} 
              {{ category|upper }} 
              {% endif %} 
              <span>{{ count }}</span>
            </a>
            {% endif %}
          </div>
          {% endfor %}
        </div>
        {% endif %}

        {% if categories|length > 1 and cat_selected != 0 or categories|length == 1 %}
        {% if compare|length > 1 %}
        <div class="Compare-header">
          <label class="toggle Compare-checkDifferent">
            <input type="checkbox" name="differentFeature" value="true" checked="checked"/>
            <span class="toggle-box"></span>
            <span class="toggle-text">{% trans 'Only differing characteristics' %}</span>
          </label>
        </div>
        {% endif %}
        {% endif %}

        {% if compare %}
        <div class="Compare-row">
          <div class="Compare-title Compare-title_blank"></div>
          <div class="Compare-products">
            {% for item in compare %}
            {% with item.product as product %}
            <div class="Compare-product">
              <div class="Compare-nameProduct Compare-nameProduct_main">{{ product.title }}</div>
              <div class="Compare-feature">
                {% if product.image %}
                <img class="Compare-pict" src="{{ product.image.url }}" alt="{{ product.title }}"/>
                {% endif %}
              </div>
            </div>
            {% endwith %}
            {% endfor %}
          </div>
        </div>

        <div class="Compare-row">
          <div class="Compare-title Compare-title_blank"></div>
          <div class="Compare-products">
            {% for item in compare %}
            {% with item.product as product %}
            <div class="Compare-product">
              <div class="Compare-nameProduct">{{ product.title }}</div>
              <div class="Compare-feature">
                <a id="add-to-cart" class="Compare-btn product" href="{% url 'order:add-to-cart' product.id %}">
                  <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                </a>
                <a id="delete-from-compare" class="Compare-btn Compare-delete" href="{% url 'user:compare_list' product.id %}">
                  <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/>
                </a>
              </div>
            </div>
            {% endwith %}
            {% endfor %}
          </div>
        </div>

        <div class="Compare-row">
          <div class="Compare-title">{% trans 'rating'|capfirst %}</div>
          <div class="Compare-products">
            {% for item in compare %}
            {% with item.product as product %}
            <div class="Compare-product">
              <div class="Compare-nameProduct">{{ product.title }}</div>
              <div class="Compare-feature">
                <div class="Rating">
                  <div class="Rating-stars">
                    {% stars rating=product.rating as range %}
                    {% for i in range %}
                    <span class="Rating-star Rating-star_view">
                      <svg xmlns="http://www.w3.org/2000/svg" width="19" height="18" viewBox="0 0 19 18">
                        <g>
                          <g>
                            <path fill="#ffc000" d="M9.5 14.925L3.629 18l1.121-6.512L0 6.875l6.564-.95L9.5 0l2.936 5.925 6.564.95-4.75 4.613L15.371 18z"></path>
                          </g>
                        </g>
                      </svg>
                    </span>
                    {% endfor %}
                    {% not_stars rating=product.rating as range %}
                    {% for i in range %}
                    <span class="Rating-star">
                      <svg xmlns="http://www.w3.org/2000/svg" width="19" height="18" viewBox="0 0 19 18">
                        <g>
                          <g>
                            <path fill="#ffc000" d="M9.5 14.925L3.629 18l1.121-6.512L0 6.875l6.564-.95L9.5 0l2.936 5.925 6.564.95-4.75 4.613L15.371 18z"></path>
                          </g>
                        </g>
                      </svg>
                    </span>
                    {% endfor %}
                  </div>
                  <div class="Rating-title">
                  </div>
                </div>
              </div>
            </div>
            {% endwith %}
            {% endfor %}
          </div>
        </div>

        {% if compare|length > 1 %}
        {% if categories|length == 1 or cat_selected != 0 %}
        {% with attributes as attributes %}
        {% for attr in attributes %}
      
        {% hide compare=compare attr=attr.attribute as hide %}
        <div class="Compare-row {% if hide %}Compare-row_hide{% endif %}">
          <div class="Compare-title">{{ attr.attribute }}</div>
          <div class="Compare-products">
            
            {% for item in compare %}
              {% with product=item.product_id %}
              
              <div class="Compare-product">
                <div class="Compare-nameProduct">{{ product.title }}</div>
                {% value_dict product=product attr=attr.attribute as value_dict %}
                <div class="Compare-feature">
                  {{ value_dict.value }} 
                    {% if value_dict.unit != None %} 
                    {{ value_dict.unit }} 
                    {% endif %}</div>
              </div>

              {% endwith %}
            {% endfor %}
          </div>
          
        </div>
        {% endfor %}
        
        {% endwith %}
        {% endif %}
        {% else %}
        <div class="Compare-row Compare-message">
          {% trans 'Not enough data to compare' %}
        </div>
        {% endif %}
        
        <div class="Compare-row">
          <div class="Compare-title">{% trans 'price'|capfirst %}</div>
          <div class="Compare-products">
          {% for item in compare %}
            {% with item.product as product %}
            <div class="Compare-product">
              <div class="Compare-nameProduct">{{ product.title }}</div>
              <div class="Compare-feature">
              {% with product.discount as discount %}
                {% if discount.type %}
                <strong class="Compare-priceOld">${{ discount.base }}</strong>
                {% endif %}
                {% if discount.base %}
                <strong class="Compare-price">${{ discount.price }}</strong>
                {% else %}
                <strong class="Compare-price">{% trans 'The product is over' %}</strong>
                {% endif %}
              {% endwith %}
              </div>
            </div>
            {% endwith %}
          {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endif %}
        {% endwith %}
      </div>
      
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}

marketplace_app/user/templates/user/historyview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
  {% include "head.html" %}
{% endblock %}

{% block header %}
  <header class="Header">
    {% include "header.html" %}
  </header>
{% endblock %}

{% block middle %}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% trans "viewing history" %}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'product:home' %}">{% trans "home" %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{% trans "viewing history" %}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section Section_column Section_columnLeft">
    <div class="wrap">
      {% include 'user/inc/_navigate_profile.html' %}
      <div class="Section-content">
      {% if views_list %}
        <div class="Cards">
          {% for view in views_list %}
          {% with view.product_id as product %}
          <div class="Card">
            {% include "card.html" %}
          </div>
          {% endwith %}
          {% endfor %}
        </div>
      {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

{% block scripts %}
  {% include "scripts.html" %}
{% endblock %}